---
# tasks file for roleweb
 - name: httpd and firewalld package install
   dnf: 
        name: httpd,firewalld
        state: latest

 - name: enabled and started httpd service
   service:
        name: "{{ item }}"
        enabled: yes
        state: started
   loop:
        - httpd 
        - firewalld

 - name: allow access to webserver( http port allow )
   firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

 - name: create index file
   template:
        src: index.html.j2
        dest: /var/www/html/index.html
